name: 'New Relic JUnit Reporter'
author: 'New Relic'
description: 'Report JUnit-formatted test run output files to New Relic.'
branding:
  icon: 'upload-cloud'
  color: 'blue'
inputs:
  ingestLicenseKey:
    description: 'Your New Relic Ingest License key.'
    required: true
  accountId:
    description: 'Your New Relic account ID. Custom events representing your test run will be posted to this account.'
    required: true
  region:
    description: 'The geographical region for your New Relic account - US or EU. Default: US'
    required: false
    default: US
  testOutputPath:
    description: 'The path to the JUnit output file.'
    required: true
  customAttributes:
    description: 'Any custom attributes to include in JSON format.'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    NEW_RELIC_INGEST_LICENSE_KEY: ${{ inputs.ingestLicenseKey }}
    NEW_RELIC_ACCOUNT_ID: ${{ inputs.accountId }}
    NEW_RELIC_REGION: ${{ inputs.region }}
    NEW_RELIC_TEST_OUTPUT_PATH: ${{ inputs.testOutputPath }}
    NEW_RELIC_CUSTOM_ATTRIBUTES: ${{ inputs.customAttributes }}
