name: Test Suite

on:
  pull_request:
  push:

jobs:
  basic_test:
    runs-on: ubuntu-latest
    name: Basic Usage Test
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Post JUnit test results to New Relic
        uses: ./
        with:
          accountId: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}
          ingestLicenseKey: ${{ secrets.NEW_RELIC_INGEST_LICENSE_KEY }}
          testOutputPath: test-output/integration.xml
